name: Coding Standards

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  # Runs PHP coding standards checks.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Logs debug information.
  # - Installs Composer dependencies (use cache if possible).
  # - Make Composer packages available globally.
  # - Logs PHP_CodeSniffer debug information.
  # - Runs PHPCS on the full codebase with warnings suppressed.
  # - Runs PHPCS on the `tests` directory without warnings suppressed.
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'xxsimoxx/xsx-compat'  }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Log debug information
        run: |
          php --version
          composer --version


      - name: Log PHPCS debug information
        run: phpcs -i

      - name: Run PHPCS on all Core files
        run: phpcs -q -n --report=checkstyle | cs2pr

      - name: Check test suite files for warnings
        run: phpcs tests -q -n --report=checkstyle | cs2pr

  # Runs the pre-commit checks.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Installs NodeJS.
  # - Sets up caching for NPM.
  # - Logs debug information.
  # - Installs NPM dependencies using install-changed to hash the `package.json` file.
  # - Run the ClassicPress pre-commit checks (JSHint, no uncommitted
  #   modifications to generated files).
  precommit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ClassicPress/ClassicPress' || github.event_name == 'pull_request' }}
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${{ true }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

 

      - name: Set up PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4
          ini-values: mysql.default_host=127.0.0.1,mysql.default_port=3306,mysql.default_socket=/var/run/mysqld/mysqld.sock
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install PHPUnit
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-8.phar
          chmod +x phpunit
          sudo mv phpunit /usr/bin/

      - name: Enable, start and initialise MySQL
        run: |
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          mysql -u root -proot < tools/local-env/mysql-init.sql
          mysql -u root -proot -e "SHOW DATABASES"

 

      - name: Run pre-commit checks
        run: grunt precommit:verify
